### ISSUE TITLE
Add Workflow to Sync GitHub Issues to DevOps

### ISSUE THREAD

**Issue by kachawla** [radius-project/bicep-types-aws#64]
Similar to https://github.com/radius-project/radius/blob/main/.github/workflows/devops-boards.yaml

test

[AB#13429](https://dev.azure.com/azure-octo/Incubations/_workitems/edit/13429)

**Comment by willtsai** [comment]
this actually exists already, and I've confirmed that the workflow is [running successfully](https://github.com/radius-project/bicep-types-aws/actions/runs/11410662319/job/31753414214): 
https://github.com/radius-project/bicep-types-aws/blob/main/.github/workflows/devops-board.yaml
